version: 3.6.0-{build}

branches:
  only:
    - master

max_jobs: 1

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

build_script:
  - cmd: dotnet pack src\Carter.csproj -c Release -o nupkgs

test_script:
  - cmd: dotnet test test\Carter.Tests\Carter.Tests.csproj

nuget:
  disable_publish_on_pr: true
  
artifacts:
  - path: '**\*.nupkg'
    name: packages
